# Specify the platform for which you are writing the Podfile
platform :ios, '11.0'

# Define your target
target 'Runner' do
  # Add Firebase pods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  # ... diğer Firebase kütüphaneleri
  
  # Diğer CocoaPods bağımlılıklarını ekleyin
end

# Flutter podlarını yükleyin
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
